---
galaxy_info:
  author: CCG
  description: Fixes networkmanager
  company: CCG
  license: license BSD
  min_ansible_version: 1.2
  platforms:
    - name: Ubuntu
      versions:
      - all
  categories:
    - system
